// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG1KKl98aoAel5Vl1WRXyWTf5KU9oYQUk',
    appId: '1:281081976374:web:2c4351b8bfc60417e66a97',
    messagingSenderId: '281081976374',
    projectId: 'noteapp-2d725',
    authDomain: 'noteapp-2d725.firebaseapp.com',
    storageBucket: 'noteapp-2d725.appspot.com',
    measurementId: 'G-T6L8SVG7FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_J1z_eew7nfVBk_BAM-w9rwTcsNi0Xf0',
    appId: '1:281081976374:android:3c2fd1bbf38248d6e66a97',
    messagingSenderId: '281081976374',
    projectId: 'noteapp-2d725',
    storageBucket: 'noteapp-2d725.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS3zw1UyJCaahEou8A19Plpwz7gF8KSUY',
    appId: '1:281081976374:ios:5f37f30aa4e1e3c3e66a97',
    messagingSenderId: '281081976374',
    projectId: 'noteapp-2d725',
    storageBucket: 'noteapp-2d725.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS3zw1UyJCaahEou8A19Plpwz7gF8KSUY',
    appId: '1:281081976374:ios:5f37f30aa4e1e3c3e66a97',
    messagingSenderId: '281081976374',
    projectId: 'noteapp-2d725',
    storageBucket: 'noteapp-2d725.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG1KKl98aoAel5Vl1WRXyWTf5KU9oYQUk',
    appId: '1:281081976374:web:5c61e70388076727e66a97',
    messagingSenderId: '281081976374',
    projectId: 'noteapp-2d725',
    authDomain: 'noteapp-2d725.firebaseapp.com',
    storageBucket: 'noteapp-2d725.appspot.com',
    measurementId: 'G-TK68BPEBNM',
  );
}
